# Generated by Django 3.1 on 2021-05-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gest_preparacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('n', models.IntegerField(default=0, verbose_name='N')),
                ('indice', models.IntegerField(default=0, verbose_name='Indice')),
                ('vector_candidato', models.JSONField(verbose_name='Vector candidato')),
                ('candidato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gest_preparacion.candidato')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_preparacion.eleccion')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'ordering': ['indice'],
            },
        ),
    ]
