# Generated by Django 3.1 on 2021-05-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gest_preparacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo_inicio', models.CharField(max_length=100, verbose_name='Código inicio')),
                ('estado_urna', models.IntegerField(choices=[(0, 'PREPARACIÓN'), (1, 'PROGRAMADA'), (2, 'LISTA'), (3, 'EN CURSO'), (4, 'CERRADA'), (5, 'CONTEO INICIADO')], default=0, verbose_name='Estado de mesa')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creacón')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('hora_cierre', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gest_preparacion.mesa')),
            ],
            options={
                'verbose_name': 'Urna',
                'verbose_name_plural': 'Urnas',
                'ordering': ['creacion', 'estado_urna'],
            },
        ),
    ]
