# Generated by Django 3.1 on 2021-05-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest_votacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('vector_cifrado', models.JSONField(verbose_name='Vector resultado')),
                ('hash_voto', models.CharField(max_length=100, unique=True, verbose_name='Hash voto')),
                ('estado_voto', models.IntegerField(choices=[(0, 'PREPARACIÓN'), (1, 'PROGRAMADA'), (2, 'LISTA'), (3, 'EN CURSO'), (4, 'CERRADA'), (5, 'CONTEO INICIADO')], default=0, verbose_name='Estado de voto')),
                ('hora_conteo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de conteo')),
                ('urna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gest_votacion.urna')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['estado_voto'],
            },
        ),
    ]
