# Generated by Django 3.1 on 2021-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_votacion', '0004_auto_20210618_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='estado_voto',
            field=models.IntegerField(choices=[(0, 'EMITIDO'), (1, 'PROGRAMADA'), (2, 'LISTA'), (3, 'EN CURSO'), (4, 'CERRADA'), (5, 'CONTEO INICIADO')], default=0, verbose_name='Estado de voto'),
        ),
    ]
