# Generated by Django 3.1 on 2021-06-19 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cifrado', '0009_clave_hash'),
        ('gest_votacion', '0005_auto_20210619_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='clave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gest_cifrado.clave'),
        ),
    ]
