# Generated by Django 3.1 on 2021-10-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_votacion', '0008_auto_20211013_1642'),
        ('gest_votacion', '0008_auto_20211001_0948'),
    ]

    operations = [
    ]
