# Generated by Django 3.1 on 2021-05-21 19:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gest_usuario', '0001_initial'),
        ('gest_cargo', '0001_initial'),
        ('gest_elector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de realización')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('etapa', models.IntegerField(choices=[(0, 'PREPARACIÓN'), (1, 'PROGRAMADA'), (2, 'LISTA'), (3, 'EN CURSO'), (4, 'CERRADA'), (5, 'CONTEO INICIADO')], default=0, verbose_name='Etapa de elección')),
                ('slug', models.SlugField(unique=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_cargo.cargo')),
            ],
            options={
                'verbose_name': 'Eleccion',
                'verbose_name_plural': 'Elecciones',
                'ordering': ['fecha', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('estado_padron', models.IntegerField(choices=[(0, 'PREPARACIÓN'), (1, 'PROGRAMADA'), (2, 'LISTA'), (3, 'EN CURSO'), (4, 'CERRADA'), (5, 'CONTEO INICIADO')], default=0, verbose_name='Etapa de elección')),
                ('slug', models.SlugField(unique=True)),
                ('eleccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gest_preparacion.eleccion')),
            ],
            options={
                'verbose_name': 'Padron',
                'verbose_name_plural': 'Padrones',
                'ordering': ['slug', 'estado_padron'],
            },
        ),
        migrations.CreateModel(
            name='PadronElector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('estado_padronelector', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Identificado'), (2, 'Votando'), (3, 'Completado'), (4, 'Suspendido')], default=0, verbose_name='Estado padron-elecctor')),
                ('hora_votacion', models.DateTimeField(blank=True, null=True, verbose_name='Hora de votación')),
                ('codigo_votacion', models.UUIDField(blank=True, null=True, verbose_name='Código de votación')),
                ('elector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_elector.elector')),
                ('padron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_preparacion.padron')),
            ],
            options={
                'unique_together': {('padron', 'elector')},
            },
        ),
        migrations.AddField(
            model_name='padron',
            name='electores',
            field=models.ManyToManyField(through='gest_preparacion.PadronElector', to='gest_elector.Elector'),
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('estado_mesa', models.IntegerField(choices=[(0, 'PREPARACIÓN'), (1, 'PROGRAMADA'), (2, 'LISTA'), (3, 'EN CURSO'), (4, 'CERRADA'), (5, 'CONTEO INICIADO')], default=0, verbose_name='Estado de mesa')),
                ('slug', models.SlugField(unique=True)),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gest_usuario.cuenta')),
                ('eleccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gest_preparacion.eleccion')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['slug', 'estado_mesa'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('estado_postulacion', models.BooleanField(default=True, verbose_name='Estado de postulación')),
                ('eleccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gest_preparacion.eleccion')),
                ('elector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gest_elector.elector')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['estado_postulacion'],
            },
        ),
    ]
