# Generated by Django 3.1 on 2021-05-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padron',
            options={'ordering': ['estado_padron'], 'verbose_name': 'Padron', 'verbose_name_plural': 'Padrones'},
        ),
        migrations.RemoveField(
            model_name='padron',
            name='slug',
        ),
        migrations.AlterField(
            model_name='padron',
            name='estado_padron',
            field=models.IntegerField(choices=[(0, 'PREPARACIÓN'), (1, 'PROGRAMADA'), (2, 'LISTA'), (3, 'EN CURSO'), (4, 'CERRADA'), (5, 'CONTEO INICIADO')], default=0, verbose_name='Etapa de padrón'),
        ),
    ]
