# Generated by Django 3.1 on 2021-05-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0002_auto_20210527_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['estado_mesa'], 'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='slug',
        ),
    ]
