# Generated by Django 3.1 on 2021-05-30 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gest_preparacion', '0003_auto_20210527_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
