# Generated by Django 3.1 on 2021-05-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0004_auto_20210530_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
