# Generated by Django 3.1 on 2021-06-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0006_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado_mesa',
            field=models.IntegerField(choices=[(0, 'CREADA'), (1, 'CON AUTORIDAD'), (2, 'LISTA'), (3, 'EN OPERACIÓN'), (4, 'CERRADA')], default=0, verbose_name='Estado de mesa'),
        ),
        migrations.AlterField(
            model_name='padron',
            name='estado_padron',
            field=models.IntegerField(choices=[(0, 'ABIERTO'), (1, 'EN OPERACIÓN'), (2, 'CERRADO')], default=0, verbose_name='Etapa de padrón'),
        ),
    ]
