# Generated by Django 3.1 on 2021-06-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest_elector', '0004_auto_20210527_0901'),
        ('gest_preparacion', '0007_auto_20210602_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='eleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_preparacion.eleccion'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='elector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_elector.elector'),
        ),
    ]
