# Generated by Django 3.1 on 2021-06-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0008_auto_20210602_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padron',
            name='estado_padron',
            field=models.IntegerField(choices=[(0, 'ABIERTO'), (1, 'LISTO'), (2, 'EN OPERACIÓN'), (3, 'CERRADO')], default=0, verbose_name='Etapa de padrón'),
        ),
    ]
