# Generated by Django 3.1 on 2021-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0009_auto_20210605_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado_mesa',
            field=models.IntegerField(choices=[(0, 'CREADA'), (1, 'CON AUTORIDAD'), (2, 'PREPARADA'), (3, 'INICIADA'), (4, 'LISTA'), (5, 'OPERATIVA'), (4, 'CERRADA')], default=0, verbose_name='Estado de mesa'),
        ),
        migrations.AlterField(
            model_name='padron',
            name='estado_padron',
            field=models.IntegerField(choices=[(0, 'ABIERTO'), (1, 'PREPARADO'), (2, 'EN OPERACIÓN'), (3, 'CERRADO')], default=0, verbose_name='Etapa de padrón'),
        ),
        migrations.AlterField(
            model_name='padronelector',
            name='estado_padronelector',
            field=models.IntegerField(choices=[(0, 'AUSENTE'), (1, 'AUTORIZADO'), (2, 'RETIRADO')], default=0, verbose_name='Estado padron-elecctor'),
        ),
    ]
