# Generated by Django 3.1 on 2021-06-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0011_auto_20210617_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado_mesa',
            field=models.IntegerField(choices=[(0, 'CREADA'), (1, 'CON AUTORIDAD'), (2, 'PREPARADA'), (3, 'INICIADA'), (4, 'LISTA'), (5, 'OPERATIVA'), (6, 'CERRADA')], default=0, verbose_name='Estado de mesa'),
        ),
    ]
