# Generated by Django 3.1 on 2021-06-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0012_auto_20210618_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='etapa',
            field=models.IntegerField(choices=[(0, 'PREPARACIÓN'), (1, 'PROGRAMADA'), (2, 'LISTA'), (3, 'EN CURSO'), (4, 'CERRADA'), (5, 'CONTEO INICIADO'), (5, 'CONTEO FINALIZADO')], default=0, verbose_name='Etapa de elección'),
        ),
    ]
