# Generated by Django 3.1 on 2021-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0014_auto_20210620_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
