# Generated by Django 3.1 on 2021-10-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0015_auto_20211013_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleccion',
            name='legajo',
            field=models.CharField(default='0001/2021', max_length=100, verbose_name='Legajo'),
            preserve_default=False,
        ),
    ]
