# Generated by Django 3.1 on 2021-11-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0018_eleccion_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='etapa',
            field=models.IntegerField(choices=[(0, 'PREPARACIÓN'), (1, 'PROGRAMADA'), (2, 'LISTA'), (3, 'EN CURSO'), (4, 'CERRADA'), (5, 'CONTEO INICIADO'), (6, 'CONTEO FINALIZADO'), (7, 'FALLIDA')], default=0, verbose_name='Etapa de elección'),
        ),
    ]
