# Generated by Django 3.1 on 2021-10-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_preparacion', '0018_eleccion_staff'),
        ('gest_preparacion', '0015_auto_20211013_0921'),
    ]

    operations = [
    ]
