# Generated by Django 3.1 on 2021-05-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='editable',
            field=models.IntegerField(choices=[(0, 'Editable'), (1, 'No Editable')], default=0, verbose_name='Estado del cargo'),
        ),
    ]
