# Generated by Django 3.1 on 2021-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cargo', '0002_auto_20210527_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='editable',
            field=models.BooleanField(default=True, verbose_name='Editable'),
        ),
    ]
