# Generated by Django 3.1 on 2021-05-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('dni', models.IntegerField(default=0, verbose_name='DNI')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre/s')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellido/s')),
                ('cuenta_u', models.BooleanField(default=False, verbose_name='Cuenta de usuario')),
            ],
            options={
                'verbose_name': 'Elector',
                'verbose_name_plural': 'Electores',
                'ordering': ['nombres', 'apellidos'],
            },
        ),
    ]
