# Generated by Django 3.1 on 2021-05-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_elector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elector',
            options={'ordering': ['nombres', 'apellidos', 'dni'], 'verbose_name': 'Elector', 'verbose_name_plural': 'Electores'},
        ),
        migrations.AddField(
            model_name='elector',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
