# Generated by Django 3.1 on 2021-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_elector', '0002_auto_20210527_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
