# Generated by Django 3.1 on 2021-10-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_elector', '0005_auto_20211013_0921'),
        ('gest_elector', '0005_auto_20211013_1642'),
    ]

    operations = [
    ]
