# Generated by Django 3.1 on 2021-05-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gest_usuario', '0001_initial'),
        ('gest_preparacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('hash', models.CharField(max_length=100, unique=True, verbose_name='Hash')),
                ('clave_publica', models.IntegerField(verbose_name='Clave pública')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacón')),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gest_usuario.cuenta')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_preparacion.eleccion')),
            ],
            options={
                'verbose_name': 'Clave',
                'verbose_name_plural': 'Claves',
                'ordering': ['eleccion', 'cuenta', 'creacion'],
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('final', models.BooleanField(default=False, verbose_name='Resultado final')),
                ('parciales', models.IntegerField(verbose_name='Parciales restantes')),
                ('vector_resultado', models.JSONField(verbose_name='Vector resultado')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creacón')),
                ('hash_final', models.CharField(max_length=100, unique=True, verbose_name='Hash final')),
                ('eleccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gest_preparacion.eleccion')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['creacion', 'final'],
            },
        ),
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('suma', models.JSONField(verbose_name='Suma parcial')),
                ('descifrado', models.BooleanField(default=False, verbose_name='Descifrado')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de obtención')),
                ('hash_final', models.CharField(max_length=100, unique=True, verbose_name='Hash')),
                ('clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_cifrado.clave')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_cifrado.resultado')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['descifrado'],
            },
        ),
    ]
