# Generated by Django 3.1 on 2021-05-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cifrado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clave',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha  y hora de creacón'),
        ),
    ]
