# Generated by Django 3.1 on 2021-06-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cifrado', '0002_auto_20210521_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaPrimo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('indice', models.IntegerField(verbose_name='indice de la secuencia')),
                ('secuencia', models.JSONField(verbose_name='Secuencia de 1250 numeros primos')),
            ],
            options={
                'verbose_name': 'SecuenciaPrimo',
                'verbose_name_plural': 'Secuencia de Primos',
                'ordering': ['indice'],
            },
        ),
    ]
