# Generated by Django 3.1 on 2021-06-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cifrado', '0003_secuenciaprimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clave',
            name='hash',
        ),
    ]
