# Generated by Django 3.1 on 2021-06-08 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest_usuario', '0002_auto_20210602_1116'),
        ('gest_cifrado', '0004_remove_clave_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clave',
            name='cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gest_usuario.cuenta'),
        ),
    ]
