# Generated by Django 3.1 on 2021-06-08 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gest_cifrado', '0005_auto_20210608_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clave',
            name='cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
