# Generated by Django 3.1 on 2021-06-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cifrado', '0006_auto_20210608_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clave',
            name='clave_publica',
        ),
        migrations.AddField(
            model_name='clave',
            name='n',
            field=models.CharField(default='', max_length=100, verbose_name='Clave pública'),
        ),
    ]
