# Generated by Django 3.1 on 2021-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cifrado', '0008_auto_20210617_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='clave',
            name='hash',
            field=models.CharField(default='ssssssssssssss', max_length=32, verbose_name='Hash'),
            preserve_default=False,
        ),
    ]
