# Generated by Django 3.1 on 2021-06-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cifrado', '0009_clave_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcial',
            name='hash_final',
            field=models.CharField(max_length=100, null=True, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='hash_final',
            field=models.CharField(max_length=100, null=True, verbose_name='Hash final'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='parciales',
            field=models.IntegerField(default=0, verbose_name='Parciales restantes'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='vector_resultado',
            field=models.JSONField(default={}, verbose_name='Vector resultado'),
        ),
    ]
