# Generated by Django 3.1 on 2021-06-21 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cifrado', '0010_auto_20210620_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcial',
            options={'ordering': ['descifrado'], 'verbose_name': 'Parcial', 'verbose_name_plural': 'Parciales'},
        ),
        migrations.AlterField(
            model_name='parcial',
            name='clave',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gest_cifrado.clave'),
        ),
    ]
